# Generated by Django 4.0.3 on 2022-04-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_listing_listing_creator_alter_bid_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
