# Generated by Django 4.0.3 on 2022-04-14 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_watchlist_title_watchlist_auction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='auction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_id', to='auctions.auction_listing'),
        ),
    ]
