# Generated by Django 4.0.3 on 2022-04-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_watchlist_auction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='auction_id',
            new_name='auction_listing',
        ),
    ]
