# Generated by Django 4.0.3 on 2022-04-15 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_auction_id_watchlist_auction_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='auction_listing',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='auction_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_watchlist', to='auctions.auction_listing'),
        ),
    ]
