# Generated by Django 4.0.3 on 2022-04-19 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_title_bid_auction_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='highest_bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Highest_bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
